name: docker

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        docker_tag: [xenial, bionic, focal]
        include:
        - docker_tag: xenial
          docker_tags: |
            i3dr/rtabmap:xenial
            i3dr/rtabmap:16.04
          docker_platforms: |
            linux/amd64
          docker_path: 'xenial'
        - docker_tag: bionic
          docker_tags: |
            i3dr/rtabmap:bionic
            i3dr/rtabmap:18.04
          docker_platforms: |
            linux/amd64
            linux/arm64
          docker_path: 'bionic'
        - docker_tag: focal
          docker_tags: |
            i3dr/rtabmap:focal
            i3dr/rtabmap:20.04
            i3dr/rtabmap:latest
          docker_platforms: |
            linux/amd64
            linux/arm64
          docker_path: 'focal'
    
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ matrix.docker_platforms }}
          file: ./docker/${{ matrix.docker_path }}/Dockerfile
          build-args: |
            ${{ matrix.docker_args }}
          tags: ${{ matrix.docker_tags }}
          cache-from: type=registry,ref=i3dr/rtabmap:${{ matrix.docker_tag }}
          cache-to: type=inline

